---
title: "Calculating PDSI and SPEI"
author: "steppe"
output:
  word_document: default
always_allow_html: true
---

Variables required:

Precipitation
Available Water Content

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(dpi = 300) 
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
```

```{r}
library(terra)
```


Create potential solar hours rasters

"Elevation, aspect and slope input values should not be reclassified into coarser categories. This could lead to incorrect results. " - r.sun man pages


```{r Create template raster for sun hours, eval = F}

template <- rast('/hdd/Geospatial_data/sunhours/input/UFO_dem_10_smooth.tif')
xy <- ext(template)

coarse_template <- rast(nrow = 100, ncol = 100, crs = crs(template),
     xmin = xy[1], xmax =	 xy[2], ymin 	=  xy[3], ymax =  xy[4], vals = 0
       )
writeRaster(coarse_template, '/hdd/Geospatial_data/sunhours/input/coarse.tif')
```

```{bash calculate sun hours in GRASS GIS, eval = F}

grass --tmp-location /hdd/Geospatial_data/sunhours/input/coarse.tif
pOUT='/hdd/Geospatial_data/sunhours/output'

for i in {1..365}
do
  rasterfari=SunHours$i
  r.sunhours sunhour=$rasterfari year=2000 day=$i --overwrite
  r.out.gdal input=$rasterfari output=$pOUT/${rasterfari} format=GTiff -c --overwrite
done

exit

```


```{r}

list.files()
d1 <- terra::rast('/hdd/Geospatial_data/sunhours/output/SunHours182')

```

# Calculation of SPEI 
```{r}
library(SPEI)

data(wichita)

# Potential Evapotransrespiration,
 # requires the monthly mean temperature, and the latitudinal centroid of the cell
wichita$PET <- thornthwaite(wichita$TMED, 37.6475) 

# the total monthly precipitation minus the 
# potential evapotransrespiration is the Water Balance
wichita$BAL <- wichita$PRCP-wichita$PET 

wichita <- ts(wichita[,-c(1,2)], end=c(2011,10), frequency=12)
plot(wichita)

# Calculate the SPEI here
spei3 <- spei(wichita[,'BAL'], scale = 3) # seasonal
spei12 <- spei(wichita[,'BAL'], scale = 12) # yearly

plot(spei3)
plot(spei12)

rm(wichita)
data(wichita)

PET <- thornthwaite(wichita$TMED, 37.6475) 

# the total monthly precipitation minus the 
# potential evapotransrespiration is the Water Balance
BAL <- wichita$PRCP-PET 

wichita <- ts(wichita[,-c(1,2)], end=c(2011,10), frequency=12)
plot(wichita)

# Calculate the SPEI here
spei1 <- spei(wichita[,'BAL'], scale = 1) # one month
spei3 <- spei(wichita[,'BAL'], scale = 3) # seasonal
spei12 <- spei(wichita[,'BAL'], scale = 12) # yearly

```

